version: "3"
services:
  app:
    build: .
    tty: true
    command: [CMD]
    environment:
      - FILENAME_PREPEND=[FILENAME_PREPEND]
    volumes: 
      - ./app:/app/
      - ./cache:/cache/
      - [SOURCE]:/input/